name: portfolio-v3-prod

services:
  portfolio-v3-prod:
    container_name: portfolio-v3-prod
    ports:
      - 3000:3000
    image: portfolio-v3-prod:latest
    env_file:
      - /opt/portfolio/env/.env.prod
    volumes:
      - /opt/portfolio/env/system-prompt.txt:/app/system-prompt.txt:ro
    networks:
      traefik_proxy:
        aliases:
          - portfolio-v3-prod
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true