name: portfolio-v3-staging

services:
  portfolio-v3-staging:
    container_name: portfolio-v3-staging
    ports:
      - 3001:3000
    image: portfolio-v3-staging:latest
    networks:
      traefik_proxy:
        aliases:
          - portfolio-v3-staging
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true