
name: "Portoflio V2 - Production Deployment"

on:
  push:
    branches:
      - main
    # Only run on changes to the relevant code
    paths:
      - portfolio/app
      - portfolio/components
      - portfolio/docker

jobs:
  deploy-repo:
    name: "Deploy repo into production"
    runs-on: [docker, self-hosted]

    steps:
      # Download repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the app and make a Docker image of it
      - name: Build Docker image
        run: docker build -t portfolio-v2-prod:latest -f portfolio/docker/prod/Dockerfile .

      # If already up, take it down
      - name: Stop and remove existing container
        run: docker compose -f portfolio/docker/prod/docker-compose.yml down || true

      # Start the app once again
      - name: Start container with Docker Compose
        run: docker compose -f portfolio/docker/prod/docker-compose.yml up -d