
name: "Portoflio V3 - Staging Deployment"

on:
  push:
    branches:
      - staging
    # Only run on changes to the relevant code
    paths:
      - 'app/**'
      - 'components/**'
      - 'docker/**'
      - 'content/**'
  workflow_dispatch:

jobs:
  deploy-repo:
    name: "Deploy repo into staging"
    runs-on: [docker, self-hosted]

    steps:
      # Download repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the app and make a Docker image of it
      - name: Build Docker image
        run: docker build -t portfolio-v3-staging:latest -f docker/staging/Dockerfile .

      # If already up, take it down
      - name: Stop and remove existing container
        run: docker compose -f docker/staging/docker-compose.yml down || true

      # Start the app once again
      - name: Start container with Docker Compose
        run: docker compose -f docker/staging/docker-compose.yml up -d